version: "3.9"

networks:
  default:
    name: kh_net

services:
  db: 
    image: mysql:8
    command: --max_allowed_packet=32505856 --wait-timeout=28800 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kamehouse
      MYSQL_DATABASE: kamehouse_development
      MYSQL_USER: kamehouse
      MYSQL_PASSWORD: kamehouse
    ports:
      - "3311:3306"
    mem_limit: 1g
    mem_reservation: 500M
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - kh-db-volume:/var/lib/mysql
  web: 
    image: kamehouse
    build: .
    stdin_open: true
    tty: true
    entrypoint: ["/app/bin/docker-entrypoint"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health_check"]
      timeout: 5s
      retries: 5
    volumes:
      - ".:/app"
      - "kh-tmp:/tmp"
    ports:
      - "3000:3000"
    mem_limit: 2g
    mem_reservation: 128M
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_NAME: kamehouse
      DB_PASSWORD: kamehouse
      DB_HOST: db

volumes:
  kh-db-volume:
  kh-tmp:
